test1/blog/urls.py
from django.urls import path,include
from blog import views 
app_name = 'blog'

urlpatterns = [
    path('', views.index,name='index'),
    path('article/<int:id>/', views.article_page, name='article_page'),
    path('edit/<int:id>/', views.edit_page,name='edit_page'),
    path('edit/action/', views.edit_action,name='edit_action'),
    path('del/<int:id>/', views.del_action,name='del_action'),
]

test1/test1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

test1/blog/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
	title=models.CharField(max_length=20,default="title")
	content=models.TextField(null=True)

	def __str__(self):
		return self.title


test1/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from . import models

def index(request):
	articles=models.Article.objects.all()
	return render(request,'blog/index.html',{'articles':articles})

def article_page(request,id):
	article=models.Article.objects.get(pk=id)
	return render(request,'blog/article_page.html',{'article':article})


def edit_page(request,id):
	if id==0:
		return render(request,'blog/edit_page.html')
	else:
		article=models.Article.objects.get(pk=id)
		return render(request,'blog/edit_page.html',{'article':article})



def edit_action(request):
	title=request.POST.get('title','title')
	content=request.POST.get('content','content')
	id_=request.POST.get('id')
	if int(id_)==0:
		models.Article.objects.create(title=title,content=content)
		articles=models.Article.objects.all()
		return render(request,'blog/index.html',{'articles':articles})

	else:
		article=models.Article.objects.get(pk=id_)
		article.title=title
		article.content=content
		article.save()
		return render(request,'blog/article_page.html',{'article':article})


def del_action(request,id):
	article=models.Article.objects.get(pk=id)
	article.delete()
	articles=models.Article.objects.all()
	return render(request,'blog/index.html',{'articles':articles})

test1/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<h1>{{ article.title }}</h1>
	<hr>
	<h3>{{ article.content }}</h3>
	<hr>
	<h3>{{ article.id }}</h3>
	<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
	<a href="{% url 'blog:del_action' article.id %}">删除文章</a>
</body>
</html>

test1/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<form action="{% url 'blog:edit_action' %}" method="post">
		{% csrf_token %}
		
			<input type="hidden" name="id" value="{{ article.id|default:0 }}">
			<label>title:</label>
			<input type="text" name="title" value={{ article.title }}>
			<br><br>
			<label>content:</label>
			<input type="text" name="content" value={{ article.content }}>
			<br><br>

		<input type="submit" name="submit"  value="submit">
	</form>
</body>
</html>

test1/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<h2><a href="{% url 'blog:edit_page' id=0 %}">new article</a></h2>
	{% for article in articles %}
		<a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
		<hr>
	{% endfor %}
</body>
</html>